# Generated by Django 2.2.5 on 2022-03-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('disc', models.TextField()),
                ('image', models.ImageField(upload_to='blog/images')),
                ('post_date', models.DateTimeField(default=-20700)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Category')),
            ],
        ),
    ]
