# Generated by Django 2.2.5 on 2022-03-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=2, upload_to='image'),
            preserve_default=False,
        ),
    ]
