# Generated by Django 2.2.5 on 2022-04-13 11:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20220413_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='long_disc',
            field=tinymce.models.HTMLField(),
        ),
    ]
